name: Flutter CI
on: 
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'beta'
    - run: flutter pub get
    - run: flutter format --set-exit-if-changed .
    - run: flutter analyze
    - run: flutter build apk
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk
    

    